// flow-typed signature: 5860d6043f59fd2024917259e2aec580
// flow-typed version: <<STUB>>/electron-open-link-in-browser_v^1.0.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-open-link-in-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-open-link-in-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-open-link-in-browser/build/electron-open-link-in-browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-open-link-in-browser/build/electron-open-link-in-browser.js' {
  declare module.exports: $Exports<'electron-open-link-in-browser/build/electron-open-link-in-browser'>;
}
declare module 'electron-open-link-in-browser/index' {
  declare module.exports: $Exports<'electron-open-link-in-browser'>;
}
declare module 'electron-open-link-in-browser/index.js' {
  declare module.exports: $Exports<'electron-open-link-in-browser'>;
}
