// flow-typed signature: 205577ae9ed3da993eef33f64e6ee139
// flow-typed version: <<STUB>>/electron-css_v^0.12.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-css/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-css/dist/index.js' {
  declare module.exports: $Exports<'electron-css/dist/index'>;
}
