// flow-typed signature: 4db8f6dcd470cafe99b8f0486610b477
// flow-typed version: <<STUB>>/react-mousetrap_v^0.2.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mousetrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mousetrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-mousetrap/__tests__/mouseTrap-test' {
  declare module.exports: any;
}

declare module 'react-mousetrap/jest.config' {
  declare module.exports: any;
}

declare module 'react-mousetrap/jest.setup' {
  declare module.exports: any;
}

declare module 'react-mousetrap/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-mousetrap/__tests__/mouseTrap-test.js' {
  declare module.exports: $Exports<'react-mousetrap/__tests__/mouseTrap-test'>;
}
declare module 'react-mousetrap/jest.config.js' {
  declare module.exports: $Exports<'react-mousetrap/jest.config'>;
}
declare module 'react-mousetrap/jest.setup.js' {
  declare module.exports: $Exports<'react-mousetrap/jest.setup'>;
}
declare module 'react-mousetrap/lib/index.js' {
  declare module.exports: $Exports<'react-mousetrap/lib/index'>;
}
