// flow-typed signature: 253a8be29c20889bbc7b1c2d24602d6a
// flow-typed version: <<STUB>>/react-files_v^2.4.7/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-files'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-files' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-files/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-files/dist/index.js' {
  declare module.exports: $Exports<'react-files/dist/index'>;
}
